<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\" />
    <Folder Include="Ressources\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ProrsbArs">
      <HintPath>..\..\..\ProrsbArs\ProrsbArs\bin\Debug\net8.0-windows\ProrsbArs.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y &quot;$(TargetDir)&quot; &quot;C:\ProgramData\Autodesk\ApplicationPlugins\$(ProjectName).bundle\Contents\&quot;&#xD;&#xA;xcopy /Y &quot;$(ProjectDir)UpgradeUpdateRvt.addin&quot; &quot;C:\ProgramData\Autodesk\ApplicationPlugins\$(ProjectName).bundle\Contents\&quot;&#xD;&#xA;xcopy /Y &quot;$(ProjectDir)\*&quot; &quot;C:\ProgramData\Autodesk\ApplicationPlugins\$(ProjectName).bundle\Contents\Ressources\&quot;&#xD;&#xA;xcopy /Y &quot;$(ProjectDir)PackageContents.xml&quot; &quot;C:\ProgramData\Autodesk\ApplicationPlugins\$(ProjectName).bundle\&quot;&#xD;&#xA;" />
  </Target>

</Project>
